// src/app/layout.tsx
import type { Metadata } from "next";
import "../../public/assets/css/admin.css";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/style.css";
import "../../public/assets/css/font_awesome.css";
import "../../public/assets/css/leaflet.css";

import DynamicScripts from "./(WebPage)/Dynamic/DynamicScripts/DynamicScripts"; // ✅ Use DynamicScripts
import AuthWrapper from "./(WebPage)/Dynamic/AuthWrapper/AuthWrapper"; // ✅ Use AuthWrapper
import { AuthProvider } from "./Providers/AuthProvider";



export const metadata: Metadata = {
  title: "Anurag | Home",
  description: "Generated by create next app",
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang="en" suppressHydrationWarning data-theme="light">
      <body style={{ overflowX: "hidden", top: 0 }}>
        <AuthProvider>
   
          {/* {style.css & animation.css */}
          <AuthWrapper>{children}</AuthWrapper>
          {/* script.js & animation.js */}
          <DynamicScripts />

       
        </AuthProvider>
      </body>
    </html>
  );
}
